# Project Identity
spring.application.name=LogicAuth Resource Tracker

# MongoDB Atlas Connection
# Successfully updated with your ishwaridn_db_user credentials
spring.data.mongodb.uri=mongodb+srv://ishwaridn_db_user:ddC0574s6s27hT4F@cluster0.xg6gmck.mongodb.net/logicauth_db?retryWrites=true&w=majority&appName=Cluster0

# Server Configuration
server.port=8080

# JSON Formatting (Makes API responses easy to read in the browser/Postman)
spring.jackson.serialization.indent_output=true

# Security / JWT Secret 
# This is used to sign your login tokens later
logicauth.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
logicauth.jwt.expiration=86400000

# Logging Levels (Useful for debugging Atlas connection issues)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG